app_info:
    name: github.com/Red-Sock/cyan-room
    version: v0.0.4
    startup_duration: 10s
environment:
    - name: proxy_server_port
      type: int
      value: 80
    - name: allowed_ips
      type: string
      value: []
    - name: allowed_users
      type: string
      value: []
