app_info:
    name: github.com/Red-Sock/cyan-room
    version: v0.0.1
    startup_duration: 10s
environment:
    - name: proxy_server_port
      type: int
      value: 80
    - name: new_variable
      type: string
      value: new string value
