name: master-actions
run-name: RELEASE
on:
  push:
    branches:
      - "master"

jobs:
  tag-release:
    runs-on: ${{ vars.UBUNTU_IMAGE }}
    steps:
      - name: Release tag
        id: release
        uses: RedSockActions/release_tag@v1.1.7
        with:
          token: ${{ github.token }}
    outputs:
      tag: ${{ steps.release.outputs.tag }}

  registry_release:
    runs-on: ${{ vars.UBUNTU_IMAGE }}
    needs:
      - tag-release
    steps:
      - name: Release image
        if: ${{ needs.tag-release.outputs.tag != '' }}
        uses: RedSockActions/release_image@v1.0.20
        with:
          REGISTRY_USER: ${{ vars.REGISTRY_USER }}
          REGISTRY_PWD:  ${{ secrets.REGISTRY_PWD }}